### ISSUE TITLE
windows的WSL的Ubuntu虚拟机可以使用吗

### ISSUE THREAD

**Issue by ghost** [Mosklia/gcc-hentai#1]
我在\usr\share\locale\zh_CN\LC_MESSAGES下不能找到gcc.mo文件，将编译好的mo文件放入文件夹再使用export LANG=zh_CN.UTF-8也没有效果，有什么办法吗

**Comment by Mosklia** [comment]
这个我不太清楚欸，后面研究一下

你要不先检查一下有没有 `xgettext` 这个命令？

**Comment by hellocym** [comment]
我在wsl和非wsl上面通过apt安装gcc，但是都没有找到gcc.mo
是不是应该通过其他方式安装？

**Comment by hellocym** [comment]
> 我在wsl和非wsl上面通过apt安装gcc，但是都没有找到gcc.mo 是不是应该通过其他方式安装？

以及gcc版本？

**Comment by RimuruChan** [comment]
我也

**Comment by Hydrostic** [comment]
@hellocym @Enmmma 你先看看自己gcc大版本号是什么 比如说gcc11.3 大版本号就是11 然后你运行 apt install gcc-11-locales 然后在文件夹下就有 gcc-11.mo 你用这个项目生成的 mo 替换就行了

**Comment by Harryl7** [comment]
@Hydrostic 请问安装之后的 gcc-11.mo 也应该在 /usr/share/locale/zh_CN/LC_MESSAGES 下吗，我的wsl里没找到

**Comment by Hydrostic** [comment]
> @Hydrostic 请问安装之后的 gcc-11.mo 也应该在 /usr/share/locale/zh_CN/LC_MESSAGES 下吗，我的wsl里没找到

是的 或者你看看有没有gcc.mo
