### ISSUE TITLE
msys2 可以用吗

### ISSUE THREAD

**Issue by SherkeyXD** [Mosklia/gcc-hentai#15]
既然 Cygwin 都可以了是不是 msys2 也可以（思考

**Comment by SherkeyXD** [comment]
不过我按照 Cygwin 的方法试了下好像没反应，msys2 装的 gcc 本身也没有 gcc.mo

**Comment by steve02081504** [comment]
怀疑你没有合理设置环境变量 所以gcc没加载对语言
```pwsh
if (Test-Command locale) {
	$env:LANG ??= $env:LANGUAGE ??= $env:LC_ALL ??= $(locale -uU)
}
```
设置好`LC_ALL`再试试？

**Comment by SherkeyXD** [comment]
> 设置好`LC_ALL`再试试？

我设置过的，但是还是不生效
<img width="616" alt="390ef0b7e7a83aa2b80d2960648a69c0" src="https://github.com/Mosklia/gcc-hentai/assets/57581480/e8872041-739e-4e2a-88b8-24d0737a1fa4">

顺便问下老哥你的shell是啥啊 怎么能在windows下面直接写linux路径的（

**Comment by steve02081504** [comment]
> 我设置过的，但是还是不生效 <img alt="390ef0b7e7a83aa2b80d2960648a69c0" width="616" src="https://user-images.githubusercontent.com/57581480/285415389-e8872041-739e-4e2a-88b8-24d0737a1fa4.png">

删除msys2目录下的mingw32和mingw64然后`pacman -Syu gcc`试试
貌似mingw的gcc不能多语言 只有msys2自己的可以

> 顺便问下老哥你的shell是啥啊 怎么能在windows下面直接写linux路径的（

powershell 自己糊了一堆屎
https://github.com/steve02081504/my-powershell-profile

**Comment by SherkeyXD** [comment]
> 删除msys2目录下的mingw32和mingw64然后`pacman -Syu gcc`试试 貌似mingw的gcc不能多语言 只有msys2自己的可以

草 可以了 感谢
