### ISSUE TITLE
winlibs build version has no gcc.mo

### ISSUE THREAD

**Issue by coolwindX** [Mosklia/gcc-hentai#17]
![image](https://github.com/Mosklia/gcc-hentai/assets/45729206/cc9076a3-84dd-4c00-a091-b9ddb34eb46a)
呃，winlibs构建的gcc都没找到gcc.mo怎么整，得换到Cygwin吗？

**Comment by Mosklia** [comment]
你可以试试直接把项目里的 gcc.po 编译成 gcc.mo 然后放进去

**Comment by coolwindX** [comment]
> 你可以试试直接把项目里的 gcc.po 编译成 gcc.mo 然后放进去

似乎没用……那我还是直接换Cygwin吧，谢谢了
